import 'analyte_model.dart';

/// Précaution commune aux médicaments : forme libre.
const String drugFreeNote =
    'Forme libre : la concentration d\'un sel (chlorhydrate, sulfate…) correspond à une autre masse molaire.';

/// Ajouts à la base d'analytes. Chaque formule brute des entrées moléculaires a
/// été **vérifiée contre une source externe indépendante** (NCI/CADD Chemical
/// Identifier Resolver et PubChem) avant ajout ; la masse molaire reste calculée
/// par le code. Statut de toutes les entrées : NON VALIDÉ.
const List<LabAnalyte> additionalAnalytes = [
  LabAnalyte(id: 'iodine', name: 'Iode (iodure, exprimé en I)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'I': 1}, formulaText: 'I', note: 'Exprimé en iodure (I⁻).', urine24h: true),
  LabAnalyte(id: 'manganese', name: 'Manganèse (Mn)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Mn': 1}, formulaText: 'Mn'),
  LabAnalyte(id: 'chromium', name: 'Chrome (Cr)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Cr': 1}, formulaText: 'Cr'),
  LabAnalyte(id: 'aluminium', name: 'Aluminium (Al)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Al': 1}, formulaText: 'Al'),
  LabAnalyte(id: 'nickel', name: 'Nickel (Ni)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Ni': 1}, formulaText: 'Ni'),
  LabAnalyte(id: 'cadmium', name: 'Cadmium (Cd)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Cd': 1}, formulaText: 'Cd'),
  LabAnalyte(id: 'arsenic', name: 'Arsenic (As)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'As': 1}, formulaText: 'As', urine24h: true),
  LabAnalyte(id: 'molybdenum', name: 'Molybdène (Mo)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Mo': 1}, formulaText: 'Mo'),
  LabAnalyte(id: 'cobalt', name: 'Cobalt (Co)', category: catElectrolytes, kind: AnalyteKind.molecular,
      formula: {'Co': 1}, formulaText: 'Co'),
  LabAnalyte(id: 'creatine', name: 'Créatine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 4, 'H': 9, 'N': 3, 'O': 2}, formulaText: 'C4H9N3O2', urine24h: true),
  LabAnalyte(id: 'carnitine', name: 'Carnitine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 7, 'H': 15, 'N': 1, 'O': 3}, formulaText: 'C7H15NO3'),
  LabAnalyte(id: 'citrate', name: 'Citrate (exprimé en acide citrique)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 6, 'H': 8, 'O': 7}, formulaText: 'C6H8O7', urine24h: true),
  LabAnalyte(id: 'oxalate', name: 'Oxalate (exprimé en acide oxalique)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 2, 'H': 2, 'O': 4}, formulaText: 'C2H2O4', urine24h: true),
  LabAnalyte(id: 'glycerol', name: 'Glycérol', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 3, 'H': 8, 'O': 3}, formulaText: 'C3H8O3'),
  LabAnalyte(id: 'glutamine', name: 'Glutamine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 5, 'H': 10, 'N': 2, 'O': 3}, formulaText: 'C5H10N2O3'),
  LabAnalyte(id: 'glycine', name: 'Glycine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 2, 'H': 5, 'N': 1, 'O': 2}, formulaText: 'C2H5NO2'),
  LabAnalyte(id: 'tyrosine', name: 'Tyrosine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 11, 'N': 1, 'O': 3}, formulaText: 'C9H11NO3'),
  LabAnalyte(id: 'cystine', name: 'Cystine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 6, 'H': 12, 'N': 2, 'O': 4, 'S': 2}, formulaText: 'C6H12N2O4S2', urine24h: true),
  LabAnalyte(id: 'acetone', name: 'Acétone', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 3, 'H': 6, 'O': 1}, formulaText: 'C3H6O'),
  LabAnalyte(id: 'acetoacetate', name: 'Acétoacétate (exprimé en acide acétoacétique)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 4, 'H': 6, 'O': 3}, formulaText: 'C4H6O3'),
  LabAnalyte(id: 'methanol', name: 'Méthanol', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 1, 'H': 4, 'O': 1}, formulaText: 'CH4O'),
  LabAnalyte(id: 'ethylene_glycol', name: 'Éthylène glycol', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 2, 'H': 6, 'O': 2}, formulaText: 'C2H6O2'),
  LabAnalyte(id: 'isopropanol', name: 'Isopropanol (propan-2-ol)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 3, 'H': 8, 'O': 1}, formulaText: 'C3H8O'),
  LabAnalyte(id: 'fructose', name: 'Fructose', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 6, 'H': 12, 'O': 6}, formulaText: 'C6H12O6'),
  LabAnalyte(id: 'galactose', name: 'Galactose', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 6, 'H': 12, 'O': 6}, formulaText: 'C6H12O6'),
  LabAnalyte(id: 'mma', name: 'Acide méthylmalonique', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 4, 'H': 6, 'O': 4}, formulaText: 'C4H6O4'),
  LabAnalyte(id: 'hiaa', name: 'Acide 5-hydroxyindolacétique (5-HIAA)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 10, 'H': 9, 'N': 1, 'O': 3}, formulaText: 'C10H9NO3', urine24h: true),
  LabAnalyte(id: 'vma', name: 'Acide vanylmandélique (VMA)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 10, 'O': 5}, formulaText: 'C9H10O5', urine24h: true),
  LabAnalyte(id: 'hva', name: 'Acide homovanillique (HVA)', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 10, 'O': 4}, formulaText: 'C9H10O4', urine24h: true),
  LabAnalyte(id: 'metanephrine', name: 'Métanéphrine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 10, 'H': 15, 'N': 1, 'O': 3}, formulaText: 'C10H15NO3', urine24h: true),
  LabAnalyte(id: 'normetanephrine', name: 'Normétanéphrine', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 13, 'N': 1, 'O': 3}, formulaText: 'C9H13NO3', urine24h: true),
  LabAnalyte(id: 'pbg', name: 'Porphobilinogène', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 10, 'H': 14, 'N': 2, 'O': 4}, formulaText: 'C10H14N2O4', urine24h: true),
  LabAnalyte(id: 'ala', name: 'Acide δ-aminolévulinique', category: catMetabolites, kind: AnalyteKind.molecular,
      formula: {'C': 5, 'H': 9, 'N': 1, 'O': 3}, formulaText: 'C5H9NO3', urine24h: true),
  LabAnalyte(id: 'thiamine', name: 'Vitamine B1 (thiamine)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 12, 'H': 17, 'N': 4, 'O': 1, 'S': 1}, formulaText: 'C12H17N4OS', note: 'Cation thiamine (sans le contre-ion chlorure ou nitrate).'),
  LabAnalyte(id: 'riboflavin', name: 'Vitamine B2 (riboflavine)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 17, 'H': 20, 'N': 4, 'O': 6}, formulaText: 'C17H20N4O6'),
  LabAnalyte(id: 'plp', name: 'Vitamine B6 (pyridoxal-5\'-phosphate)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 10, 'N': 1, 'O': 6, 'P': 1}, formulaText: 'C8H10NO6P', note: 'Forme active de la vitamine B6.'),
  LabAnalyte(id: 'pyridoxine', name: 'Vitamine B6 (pyridoxine)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 11, 'N': 1, 'O': 3}, formulaText: 'C8H11NO3'),
  LabAnalyte(id: 'niacin', name: 'Vitamine PP (niacine)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 6, 'H': 5, 'N': 1, 'O': 2}, formulaText: 'C6H5NO2'),
  LabAnalyte(id: 'biotin', name: 'Biotine', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 10, 'H': 16, 'N': 2, 'O': 3, 'S': 1}, formulaText: 'C10H16N2O3S'),
  LabAnalyte(id: 'pantothenic', name: 'Acide pantothénique', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 17, 'N': 1, 'O': 5}, formulaText: 'C9H17NO5'),
  LabAnalyte(id: 'retinol', name: 'Vitamine A (rétinol)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 20, 'H': 30, 'O': 1}, formulaText: 'C20H30O'),
  LabAnalyte(id: 'tocopherol', name: 'Vitamine E (α-tocophérol)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 29, 'H': 50, 'O': 2}, formulaText: 'C29H50O2'),
  LabAnalyte(id: 'phylloquinone', name: 'Vitamine K1 (phylloquinone)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 31, 'H': 46, 'O': 2}, formulaText: 'C31H46O2'),
  LabAnalyte(id: 'calcitriol', name: '1,25-dihydroxyvitamine D (calcitriol)', category: catVitamins, kind: AnalyteKind.molecular,
      formula: {'C': 27, 'H': 44, 'O': 3}, formulaText: 'C27H44O3'),
  LabAnalyte(id: 'aldosterone', name: 'Aldostérone', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 21, 'H': 28, 'O': 5}, formulaText: 'C21H28O5', urine24h: true),
  LabAnalyte(id: 'oh17p', name: '17-hydroxyprogestérone', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 21, 'H': 30, 'O': 3}, formulaText: 'C21H30O3'),
  LabAnalyte(id: 'androstenedione', name: 'Androstènedione', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 19, 'H': 26, 'O': 2}, formulaText: 'C19H26O2'),
  LabAnalyte(id: 'dhea', name: 'DHEA', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 19, 'H': 28, 'O': 2}, formulaText: 'C19H28O2'),
  LabAnalyte(id: 'dht', name: 'Dihydrotestostérone', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 19, 'H': 30, 'O': 2}, formulaText: 'C19H30O2'),
  LabAnalyte(id: 'estrone', name: 'Estrone', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 18, 'H': 22, 'O': 2}, formulaText: 'C18H22O2'),
  LabAnalyte(id: 'estriol', name: 'Estriol', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 18, 'H': 24, 'O': 3}, formulaText: 'C18H24O3'),
  LabAnalyte(id: 'cortisone', name: 'Cortisone', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 21, 'H': 28, 'O': 5}, formulaText: 'C21H28O5', urine24h: true),
  LabAnalyte(id: 'melatonin', name: 'Mélatonine', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 13, 'H': 16, 'N': 2, 'O': 2}, formulaText: 'C13H16N2O2'),
  LabAnalyte(id: 'serotonin', name: 'Sérotonine', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 10, 'H': 12, 'N': 2, 'O': 1}, formulaText: 'C10H12N2O', urine24h: true),
  LabAnalyte(id: 'dopamine', name: 'Dopamine', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 11, 'N': 1, 'O': 2}, formulaText: 'C8H11NO2', urine24h: true),
  LabAnalyte(id: 'epinephrine', name: 'Adrénaline (épinéphrine)', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 13, 'N': 1, 'O': 3}, formulaText: 'C9H13NO3', urine24h: true),
  LabAnalyte(id: 'norepinephrine', name: 'Noradrénaline (norépinéphrine)', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 11, 'N': 1, 'O': 3}, formulaText: 'C8H11NO3', urine24h: true),
  LabAnalyte(id: 'histamine', name: 'Histamine', category: catHormones, kind: AnalyteKind.molecular,
      formula: {'C': 5, 'H': 9, 'N': 3}, formulaText: 'C5H9N3'),
  LabAnalyte(id: 'caffeine', name: 'Caféine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 10, 'N': 4, 'O': 2}, formulaText: 'C8H10N4O2', note: drugFreeNote),
  LabAnalyte(id: 'ibuprofen', name: 'Ibuprofène', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 13, 'H': 18, 'O': 2}, formulaText: 'C13H18O2', note: drugFreeNote),
  LabAnalyte(id: 'aspirin', name: 'Acide acétylsalicylique (aspirine)', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 8, 'O': 4}, formulaText: 'C9H8O4', note: drugFreeNote),
  LabAnalyte(id: 'warfarin', name: 'Warfarine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 19, 'H': 16, 'O': 4}, formulaText: 'C19H16O4', note: drugFreeNote),
  LabAnalyte(id: 'metformin', name: 'Metformine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 4, 'H': 11, 'N': 5}, formulaText: 'C4H11N5', note: drugFreeNote),
  LabAnalyte(id: 'methotrexate', name: 'Méthotrexate', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 20, 'H': 22, 'N': 8, 'O': 5}, formulaText: 'C20H22N8O5', note: drugFreeNote),
  LabAnalyte(id: 'cyclosporine', name: 'Ciclosporine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 62, 'H': 111, 'N': 11, 'O': 12}, formulaText: 'C62H111N11O12', note: drugFreeNote),
  LabAnalyte(id: 'tacrolimus', name: 'Tacrolimus', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 44, 'H': 69, 'N': 1, 'O': 12}, formulaText: 'C44H69NO12', note: drugFreeNote),
  LabAnalyte(id: 'mycophenolic', name: 'Acide mycophénolique', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 17, 'H': 20, 'O': 6}, formulaText: 'C17H20O6', note: drugFreeNote),
  LabAnalyte(id: 'vancomycin', name: 'Vancomycine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 66, 'H': 75, 'Cl': 2, 'N': 9, 'O': 24}, formulaText: 'C66H75Cl2N9O24', note: drugFreeNote),
  LabAnalyte(id: 'amikacin', name: 'Amikacine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 22, 'H': 43, 'N': 5, 'O': 13}, formulaText: 'C22H43N5O13', note: drugFreeNote),
  LabAnalyte(id: 'tobramycin', name: 'Tobramycine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 18, 'H': 37, 'N': 5, 'O': 9}, formulaText: 'C18H37N5O9', note: drugFreeNote),
  LabAnalyte(id: 'lamotrigine', name: 'Lamotrigine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 9, 'H': 7, 'Cl': 2, 'N': 5}, formulaText: 'C9H7Cl2N5', note: drugFreeNote),
  LabAnalyte(id: 'levetiracetam', name: 'Lévétiracétam', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 8, 'H': 14, 'N': 2, 'O': 2}, formulaText: 'C8H14N2O2', note: drugFreeNote),
  LabAnalyte(id: 'topiramate', name: 'Topiramate', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 12, 'H': 21, 'N': 1, 'O': 8, 'S': 1}, formulaText: 'C12H21NO8S', note: drugFreeNote),
  LabAnalyte(id: 'primidone', name: 'Primidone', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 12, 'H': 14, 'N': 2, 'O': 2}, formulaText: 'C12H14N2O2', note: drugFreeNote),
  LabAnalyte(id: 'clonazepam', name: 'Clonazépam', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 15, 'H': 10, 'Cl': 1, 'N': 3, 'O': 3}, formulaText: 'C15H10ClN3O3', note: drugFreeNote),
  LabAnalyte(id: 'diazepam', name: 'Diazépam', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 16, 'H': 13, 'Cl': 1, 'N': 2, 'O': 1}, formulaText: 'C16H13ClN2O', note: drugFreeNote),
  LabAnalyte(id: 'morphine', name: 'Morphine', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 17, 'H': 19, 'N': 1, 'O': 3}, formulaText: 'C17H19NO3', note: drugFreeNote),
  LabAnalyte(id: 'amitriptyline', name: 'Amitriptyline', category: catDrugs, kind: AnalyteKind.molecular,
      formula: {'C': 20, 'H': 23, 'N': 1}, formulaText: 'C20H23N', note: drugFreeNote),
  LabAnalyte(id: 'haptoglobin', name: 'Haptoglobine', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'ceruloplasmin', name: 'Céruloplasmine', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'prealbumin', name: 'Préalbumine (transthyrétine)', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'a1at', name: 'α1-antitrypsine', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'c3', name: 'Complément C3', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'c4', name: 'Complément C4', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'myoglobin', name: 'Myoglobine', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'afp', name: 'Alpha-fœtoprotéine (AFP)', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'cea', name: 'Antigène carcino-embryonnaire (ACE)', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'pth', name: 'Parathormone (PTH)', category: catProteins, kind: AnalyteKind.massOnly,
      note: massOnlyNote),
  LabAnalyte(id: 'lpa', name: 'Lipoprotéine(a) — masse', category: catProteins, kind: AnalyteKind.massOnly,
      note: '$massOnlyNote Lp(a) en nmol/L et en mg/dL ne sont pas convertibles par un facteur fixe (taille d\'isoforme variable).'),
  LabAnalyte(id: 'prolactin', name: 'Prolactine', category: catProteins, kind: AnalyteKind.massOnly,
      note: '$massOnlyNote Les mUI/L dépendent de l\'étalon du dosage : aucun facteur n\'est fourni.'),
  LabAnalyte(id: 'acid_phosphatase', name: 'Phosphatase acide', category: catEnzymes, kind: AnalyteKind.enzyme),
  LabAnalyte(id: 'ace', name: 'Enzyme de conversion de l\'angiotensine (ECA)', category: catEnzymes, kind: AnalyteKind.enzyme),
  LabAnalyte(id: 'ada', name: 'Adénosine désaminase (ADA)', category: catEnzymes, kind: AnalyteKind.enzyme),
  LabAnalyte(id: 'gldh', name: 'Glutamate déshydrogénase (GLDH)', category: catEnzymes, kind: AnalyteKind.enzyme),
  LabAnalyte(id: 'sperm_concentration', name: 'Spermatozoïdes (concentration)', category: catHematology, kind: AnalyteKind.cellCount),
  LabAnalyte(id: 'csf_cells', name: 'Cellules du liquide céphalo-rachidien', category: catHematology, kind: AnalyteKind.cellCount),
  LabAnalyte(id: 'urine_cells', name: 'Cellules urinaires (leucocytes, hématies)', category: catHematology, kind: AnalyteKind.cellCount),
  LabAnalyte(id: 'blood_pressure', name: 'Pression artérielle', category: catPhysiology, kind: AnalyteKind.pressure),
];
